# Configuracao do datasource
spring.datasource:
  url: jdbc:mysql://localhost:3306/curso_spring
  username: root
  password:
  driver-class-name: com.mysql.cj.jdbc.Driver
  initialization-mode: never
    
# configuracao do jpa
spring.jpa:
  hibernate:
    ddl-auto: none
  show-sql: false
  properties:
    hibernate:
      format_sql: true 
  defer-datasource-initialization: false
  database-platform: org.hibernate.dialect.MySQL5Dialect