# Propriedades da aplicacao Spring Boot
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      
# Configuracao do datasource
spring.datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  password:
  driver-class-name: org.h2.Driver
  initialization-mode: always
    
# Configuracao do jpa
spring.jpa:
  hibernate:
    ddl-auto: create
  show-sql: true
  properties:
    hibernate:
      format_sql: true 
  defer-datasource-initialization: true
  database-platform: org.hibernate.dialect.H2Dialect