INSERT INTO CATEGORIA VALUES (1, 'Informática')
INSERT INTO CATEGORIA VALUES (2, 'Escritório')

INSERT INTO PRODUTO VALUES (1, 'Computador', 2000.00)
INSERT INTO PRODUTO VALUES (2, 'Impressora', 800.00)
INSERT INTO PRODUTO VALUES (3, 'Mouse', 80.00)

INSERT INTO PRODUTO_CATEGORIA VALUES (1, 1)
INSERT INTO PRODUTO_CATEGORIA VALUES (2, 1)
INSERT INTO PRODUTO_CATEGORIA VALUES (3, 1)
INSERT INTO PRODUTO_CATEGORIA VALUES (2, 2)